name: CI/CD Pipeline Just Smile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build the Application
        run: mvn clean package --file pom.xml

      - name: Run Tests
        run: mvn test

  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Docker Tag
        id: tag
        run: echo "TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t khchimiothmen/just_smile:${{ env.TAG }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: docker push khchimiothmen/just_smile:${{ env.TAG }}

  notify:
    name: Notification
    runs-on: ubuntu-latest
    needs: [build, docker-build-push]
    if: failure() # Only run this job if the previous jobs fail
    steps:
      - name: Send Email Notification
        uses: mikepenz/action-send-mail@v1.2.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'CI/CD Pipeline Failure Notification'
          body: 'The CI/CD pipeline failed. Please check the GitHub Actions logs for more details.'
          to: khchimiothmen@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
