name: CI/CD Pipeline Just Smile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3


      # Set up Java Development Kit (JDK) 17
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17


      # Build the application using Maven
      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      # Generate a Docker tag based on the current date and time
      - name: Generate Docker Tag
        id: tag
        run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # Build the Docker image using the generated tag
      - name: Build Docker image
        run: docker build -t khchimiothmen/just_smile:latest .

      # Log in to Docker Hub using credentials from secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push khchimiothmen/just_smile:latest
