name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: build and deploy first job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      # Step to generate a Docker tag based on the current timestamp
      - name: Generate Docker Tag
        id: tag
        run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t khchimiothmen/just_smile:${{ env.tag }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push khchimiothmen/just_smile:${{ env.tag }}
